### ISSUE TITLE
Sample wanted for kunalsheth/units-of-measure

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#34]
## About the library

- *Description*: Type-safe dimensional analysis and unit conversion in Kotlin. 
- *GitHub*: https://github.com/kunalsheth/units-of-measure
- *Official website*: http://units.kunalsheth.info/

## What the sample could do

Show how to works with different units of lenght, weight, speed,, ...

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by douglascamata** [comment]
Hey @jmfayard, can I work on this after finishing the Dagger one?

**Comment by LouisCAD** [comment]
@jmfayard Since this one is using a Kotlin compiler plugin and that API is not stabilized yet and performance measurement is not straightforward, I think we should isolate it in a module or a project.

Once we decide how to organize the project around this, we should edit the contributing guide for kapt and third-party Kotlin compiler plugin dependent libraries.

**Comment by jmfayard** [comment]
If it requires a Kotlin compiler plugin, not worth the complexity, I'm closing this issue
